// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go-enum
// DO NOT EDIT!

package workflow

import (
	"fmt"
	"strings"
)

const (
	// StepStatusINITIAL is a StepStatus of type INITIAL
	StepStatusINITIAL StepStatus = iota
	// StepStatusRUNNING is a StepStatus of type RUNNING
	StepStatusRUNNING
	// StepStatusDONE is a StepStatus of type DONE
	StepStatusDONE
	// StepStatusERROR is a StepStatus of type ERROR
	StepStatusERROR
	// StepStatusCANCELED is a StepStatus of type CANCELED
	StepStatusCANCELED
)

const _StepStatusName = "INITIALRUNNINGDONEERRORCANCELED"

var _StepStatusMap = map[StepStatus]string{
	0: _StepStatusName[0:7],
	1: _StepStatusName[7:14],
	2: _StepStatusName[14:18],
	3: _StepStatusName[18:23],
	4: _StepStatusName[23:31],
}

func (i StepStatus) String() string {
	if str, ok := _StepStatusMap[i]; ok {
		return str
	}
	return fmt.Sprintf("StepStatus(%d)", i)
}

var _StepStatusValue = map[string]StepStatus{
	_StepStatusName[0:7]:                    0,
	strings.ToLower(_StepStatusName[0:7]):   0,
	_StepStatusName[7:14]:                   1,
	strings.ToLower(_StepStatusName[7:14]):  1,
	_StepStatusName[14:18]:                  2,
	strings.ToLower(_StepStatusName[14:18]): 2,
	_StepStatusName[18:23]:                  3,
	strings.ToLower(_StepStatusName[18:23]): 3,
	_StepStatusName[23:31]:                  4,
	strings.ToLower(_StepStatusName[23:31]): 4,
}

// ParseStepStatus attempts to convert a string to a StepStatus
func ParseStepStatus(name string) (StepStatus, error) {
	if x, ok := _StepStatusValue[name]; ok {
		return StepStatus(x), nil
	}
	return StepStatus(0), fmt.Errorf("%s is not a valid StepStatus", name)
}
