// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=DeploymentStatus structs.go"; DO NOT EDIT.

package deployments

import "strconv"

const _DeploymentStatus_name = "startOfDepStatusConstINITIALDEPLOYMENT_IN_PROGRESSDEPLOYEDUNDEPLOYMENT_IN_PROGRESSUNDEPLOYEDDEPLOYMENT_FAILEDUNDEPLOYMENT_FAILEDSCALING_IN_PROGRESSendOfDepStatusConst"

var _DeploymentStatus_index = [...]uint8{0, 21, 28, 50, 58, 82, 92, 109, 128, 147, 166}

func (i DeploymentStatus) String() string {
	if i < 0 || i >= DeploymentStatus(len(_DeploymentStatus_index)-1) {
		return "DeploymentStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeploymentStatus_name[_DeploymentStatus_index[i]:_DeploymentStatus_index[i+1]]
}
