// Code generated by go-enum
// DO NOT EDIT!

package tasks

import (
	"fmt"
	"strings"
)

const (
	// ActivityTypeDelegate is a ActivityType of type Delegate
	ActivityTypeDelegate ActivityType = iota
	// ActivityTypeSetState is a ActivityType of type Set-State
	ActivityTypeSetState
	// ActivityTypeCallOperation is a ActivityType of type Call-Operation
	ActivityTypeCallOperation
	// ActivityTypeInline is a ActivityType of type Inline
	ActivityTypeInline
)

const _ActivityTypeName = "delegateset-statecall-operationinline"

var _ActivityTypeMap = map[ActivityType]string{
	0: _ActivityTypeName[0:8],
	1: _ActivityTypeName[8:17],
	2: _ActivityTypeName[17:31],
	3: _ActivityTypeName[31:37],
}

func (i ActivityType) String() string {
	if str, ok := _ActivityTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ActivityType(%d)", i)
}

var _ActivityTypeValue = map[string]ActivityType{
	_ActivityTypeName[0:8]:                    0,
	strings.ToLower(_ActivityTypeName[0:8]):   0,
	_ActivityTypeName[8:17]:                   1,
	strings.ToLower(_ActivityTypeName[8:17]):  1,
	_ActivityTypeName[17:31]:                  2,
	strings.ToLower(_ActivityTypeName[17:31]): 2,
	_ActivityTypeName[31:37]:                  3,
	strings.ToLower(_ActivityTypeName[31:37]): 3,
}

// ParseActivityType attempts to convert a string to a ActivityType
func ParseActivityType(name string) (ActivityType, error) {
	if x, ok := _ActivityTypeValue[name]; ok {
		return ActivityType(x), nil
	}
	return ActivityType(0), fmt.Errorf("%s is not a valid ActivityType", name)
}
