// Copyright 2018 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "stringer -type=TaskStatus,TaskType -output=structs_string.go structs.go"; DO NOT EDIT.

package tasks

import "strconv"

const _TaskStatus_name = "INITIALRUNNINGDONEFAILEDCANCELED"

var _TaskStatus_index = [...]uint8{0, 7, 14, 18, 24, 32}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}

const _TaskType_name = "DeployUnDeployScaleOutScaleInPurgeCustomCommandCustomWorkflowQuery"

var _TaskType_index = [...]uint8{0, 6, 14, 22, 29, 34, 47, 61, 66}

func (i TaskType) String() string {
	if i < 0 || i >= TaskType(len(_TaskType_index)-1) {
		return "TaskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskType_name[_TaskType_index[i]:_TaskType_index[i+1]]
}
