// Code generated by "stringer -type=TaskStatus,TaskType -output=structs_string.go structs.go"; DO NOT EDIT

package tasks

import "fmt"

const _TaskStatus_name = "INITIALRUNNINGDONEFAILEDCANCELED"

var _TaskStatus_index = [...]uint8{0, 7, 14, 18, 24, 32}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return fmt.Sprintf("TaskStatus(%d)", i)
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}

const _TaskType_name = "DeployUnDeployPurge"

var _TaskType_index = [...]uint8{0, 6, 14, 19}

func (i TaskType) String() string {
	if i < 0 || i >= TaskType(len(_TaskType_index)-1) {
		return fmt.Sprintf("TaskType(%d)", i)
	}
	return _TaskType_name[_TaskType_index[i]:_TaskType_index[i+1]]
}
