// Copyright 2019 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package datatypes

// ProvisioningCredential is the generated representation of yorc.datatypes.ProvisioningCredential data type
type ProvisioningCredential struct {
	Credential
	// The token used as a credential for authorization or access to a networked resource.
	Token string `mapstructure:"token" json:"token,omitempty"`
	// The user (name or ID) used as a credential for authorization or access to a networked resource.
	User string `mapstructure:"user" json:"user,omitempty"`
}

// TLSClientConfig is the generated representation of yorc.datatypes.TLSClientConfig data type
type TLSClientConfig struct {
	Root
	// PEM-encoded client certificate authority content used for TLS configuration.
	CaCert string `mapstructure:"ca_cert" json:"ca_cert,omitempty"`
	// PEM-encoded client certificate content used for TLS configuration.
	ClientCert string `mapstructure:"client_cert" json:"client_cert,omitempty"`
	// PEM-encoded client private key content used for TLS configuration.
	ClientKey string `mapstructure:"client_key" json:"client_key,omitempty"`
	// Controls whether a client verifies the server’s certificate chain and host name. If set to true, TLS accepts any certificate presented by the server and any host name in that certificate
	SkipVerify bool `mapstructure:"skip_verify" json:"skip_verify,omitempty"`
}
