// Copyright 2019 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package datatypes

// GoogleEncryptionKey is the generated representation of yorc.datatypes.google.EncryptionKey data type
type GoogleEncryptionKey struct {
	Root
	// Specifies a 256-bit customer-supplied encryption key, encoded in RFC 4648 base64 to either encrypt or decrypt this resource.
	RawKey string `mapstructure:"raw_key" json:"raw_key,omitempty"`
	// The RFC 4648 base64 encoded SHA-256 hash of the customer-supplied encryption key that protects this resource.
	Sha256 string `mapstructure:"sha256" json:"sha256,omitempty"`
}

// GoogleIPRange is the generated representation of yorc.datatypes.google.IPRange data type
type GoogleIPRange struct {
	Root
	// The range of IP addresses belonging to this range. Ranges must be unique and non-overlapping with all primary and secondary IP ranges within a network. Only IPv4 is supported.
	IPCidrRange string `mapstructure:"ip_cidr_range" json:"ip_cidr_range,omitempty"`
	// The name of this IP range, used when adding an alias IP range to a VM instance. The name must be 1-63 characters long, and comply with RFC1035. The name must be unique within a subnetwork.
	Name string `mapstructure:"name" json:"name,omitempty"`
}

// GoogleScratchDisk is the generated representation of yorc.datatypes.google.ScratchDisk data type
type GoogleScratchDisk struct {
	Root
	// The disk interface to use for attaching the scratch disks; either SCSI or NVME. Defaults to SCSI.
	Interface string `mapstructure:"interface" json:"interface,omitempty"`
}

// GoogleSubnetwork is the generated representation of yorc.datatypes.google.Subnetwork data type
type GoogleSubnetwork struct {
	Root
	// Whether to enable flow logging for this subnetwork.
	EnableFlowLogs bool `mapstructure:"enable_flow_logs" json:"enable_flow_logs,omitempty"`
	// The range of internal addresses that are owned by this sub-network. For example, 10.0.0.0/8 or 192.168.0.0/16. Ranges must be unique and non-overlapping within a network. Only IPv4 is supported.
	IPCidrRange string `mapstructure:"ip_cidr_range" json:"ip_cidr_range,omitempty"`
	// The name of the resource, provided by the client when initially creating the resource. The name must be 1-63 characters long, and comply with RFC1035. Specifically, the name must be 1-63 characters long and match the regular expression [a-z]([-a-z0-9]*[a-z0-9])? which means the first character must be a lowercase letter, and all following characters must be a dash, lowercase letter, or digit, except the last character, which cannot be a dash.
	Name string `mapstructure:"name" json:"name,omitempty"`
	// Whether the VMs in this subnet can access Google services without assigned external IP addresses.
	PrivateIPGoogleAccess bool `mapstructure:"private_ip_google_access" json:"private_ip_google_access,omitempty"`
	// The ID of the project in which the resource belongs. If it is not provided, the infrastructure location project is used.
	Project string `mapstructure:"project" json:"project,omitempty"`
	// The Region in which this subnet should reside.
	Region string `mapstructure:"region" json:"region,omitempty"`
	// A list of configurations for secondary IP ranges for VM instances contained in this sub-network. The primary IP of such VM must belong to the primary ip_cidr_range of the sub-network. The alias IPs may belong to either primary or secondary ranges.
	SecondaryIPRanges []GoogleIPRange `mapstructure:"secondary_ip_ranges" json:"secondary_ip_ranges,omitempty"`
}
