// Copyright 2019 Bull S.A.S. Atos Technologies - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tdt2go
// DO NOT EDIT! ANY CHANGES MAY BE OVERWRITTEN.

package datatypes

// OSBootVolume is the generated representation of yorc.datatypes.openstack.BootVolume data type
type OSBootVolume struct {
	Root
	// Delete the volume upon termination of the instance
	DeleteOnTermination bool `mapstructure:"delete_on_termination" json:"delete_on_termination,omitempty"`
	// Destination type, possible values are 'volume' or 'local'
	Destination string `mapstructure:"destination" json:"destination,omitempty"`
	// Size of volume to create (default unit is MB). Required when source=image and destination=volume, source=blank and destination=local, or source=blank and destination=volume
	Size ScalarUnitSize `mapstructure:"size" json:"size,omitempty"`
	// Source type of the device. Must be one of 'blank', 'image', 'volume', or 'snapshot'
	Source string `mapstructure:"source" json:"source,omitempty"`
	// UUID of the image, volume, or snapshot. Required unless source is set to 'blank'
	UUID string `mapstructure:"uuid" json:"uuid,omitempty"`
}
