#!/usr/bin/env bash
#
# Starlings
# Copyright (C) 2015 Bull S.A.S. - All rights reserved
#
echo "args: $@"
env
INSTALL_DIR=$(eval readlink -f "${INSTALL_DIR}")

#set -x

source ${utils_scripts}/utils.sh

install_dnsmasq () {
    if [[ ! -e /etc/dnsmasq.conf ]] || [[ "$(grep -c "This file was generated by Starlings" /etc/dnsmasq.conf)" == "0" ]]
    then
        bash ${utils_scripts}/install-components.sh dnsmasq
        sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.ori
        sudo cp ${scripts}/config/dnsmasq.conf /etc/dnsmasq.conf
        case "$(get_os_distribution)" in
            "ubuntu" | "debian" | "mint")
                echo -e "\nIGNORE_RESOLVCONF=yes\n" | sudo tee -a /etc/default/dnsmasq > /dev/null 2>&1
                ;;
             "centos" | "redhat" | "fedora")
                sudo systemctl enable dnsmasq
                sudo cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
                echo -e "\nresolv-file=/etc/resolv.dnsmasq.conf\n" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
                sudo sed -i -e "/PEERDNS/ s/^/#/g" /etc/sysconfig/network-scripts/ifcfg-eth*
                echo -e "\nPEERDNS=no\n" | sudo tee -a /etc/sysconfig/network-scripts/ifcfg-eth* > /dev/null 2>&1
                echo -e "# Generated with starlings to enable dnsmasq\n\nnameserver 127.0.0.1\n" | sudo tee /etc/resolv.conf > /dev/null 2>&1
                ;;
        esac
        sudo service dnsmasq restart
    fi
}


if [[ "${INSTALL_DNSMASQ}" == "true" ]]; then
    log "info" "Installing DnsMasq"
    install_dnsmasq
fi

mkdir -p "${INSTALL_DIR}/logs" "${INSTALL_DIR}/work" "${INSTALL_DIR}/config"
cp ${scripts}/consul "${INSTALL_DIR}/"
chmod +x ${INSTALL_DIR}/consul

sed -e "s@#INSTALL_DIR#@${INSTALL_DIR}@g" -e "s/#IP#/${IP_ADDRESS}/g"  ${scripts}/config/1_main_conf.json > "${INSTALL_DIR}/config/1_main_conf.json"

log info "Consul installed in ${INSTALL_DIR}"
