#!/usr/bin/with-contenv sh

consul_started="1"

while [ "${consul_started}" != "0" ]
do
    sleep 2
    consul info > /dev/null
    consul_started="$?"
done

cd /var/janus
exec s6-setuidgid janus env HOME=/var/janus /bin/bash --login -c "/usr/local/bin/janus server";
