// Code generated by "stringer -type=FieldType,LogLevel -output=log_entries_string.go"; DO NOT EDIT.

package events

import "fmt"

const _FieldType_name = "WorkFlowIDExecutionIDNodeIDInstanceIDInterfaceIDOperationIDTypeID"

var _FieldType_index = [...]uint8{0, 10, 21, 27, 37, 48, 59, 65}

func (i FieldType) String() string {
	if i < 0 || i >= FieldType(len(_FieldType_index)-1) {
		return fmt.Sprintf("FieldType(%d)", i)
	}
	return _FieldType_name[_FieldType_index[i]:_FieldType_index[i+1]]
}

const _LogLevel_name = "INFODEBUGTRACEWARNERROR"

var _LogLevel_index = [...]uint8{0, 4, 9, 14, 18, 23}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return fmt.Sprintf("LogLevel(%d)", i)
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
