// Code generated by "stringer -type=LogLevel -output=log_level_string.go"; DO NOT EDIT.

package events

import "strconv"

const _LogLevel_name = "INFODEBUGWARNERROR"

var _LogLevel_index = [...]uint8{0, 4, 9, 13, 18}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
