name: "Yorc GH Actions Build"

on: [push, pull_request]


defaults:
  run:
    shell: bash

jobs:

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/golang@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup jfrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SERVER_1 }}

      - name: Ping Artifactory with jfrog CLI
        run: |
          # Ping the server
          jfrog rt ping

      # - name: Generate artifacts
      #   run: |
      #     ./build/zip_csar.sh
      # - name: Deploy artifacts to Artifactory
      #   run: |
      #     ./build/deploy_artifactory.sh
